# 21.1 浏览器错误报告- 21.2错误处理

## 21.1 浏览器错误报告

所有桌面浏览器都会在控制台中暴露错误，这些错误在开发者工具的控制台中显示

## 21.2.1 try/catch 语句

`try/catch`语句用于在可能出错的执行程序的监测，如果发生错误，会在 `catch`块中抛出错误信息，执行其中的内容。

### 1.finally 语句

`finally` 是一个可选的语句，值得注意的一点是，如果使用了 `finally` 语句，就无法通过 `try` 和`catch`块阻止其执行了，并且 `try`块或`catch` 块的 `return`语句都会被忽略。例如：

~~~js
function test () {
  try{
  return 1;
} catch (error){
  return 2
} finally {
 return 3 
}
}
 test () // 3
~~~

上面这段例子会返回3，`try`块或`catch` 块的 `return`语句被忽略了。

声明了` finally` 块之后，`catch` 块语句会变成可选的（它们两个有一个是必须的即可)

### 2.错误类型

ECMA-262 定义了以下错误类型：

[`EvalError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/EvalError)

创建一个 error 实例，表示错误的原因：与 [`eval()`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/eval) 有关。

[`RangeError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RangeError)

创建一个 error 实例，表示错误的原因：数值变量或参数超出其有效范围。

[`ReferenceError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError)

创建一个 error 实例，表示错误的原因：无效引用。

[`SyntaxError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError)

创建一个 error 实例，表示错误的原因：语法错误。

[`TypeError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

创建一个 error 实例，表示错误的原因：变量或参数不属于有效类型。

[`URIError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/URIError)

创建一个 error 实例，表示错误的原因：给 [`encodeURI()`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) 或 [`decodeURI()`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) 传递的参数无效。

[`AggregateError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/AggregateError)

创建一个 error 实例，其中包裹了由一个操作产生且需要报告的多个错误。如：[`Promise.any()`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/any) 产生的错误。

[`InternalError`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/InternalError) 非标准

创建一个代表 Javascript 引擎内部错误的异常抛出的实例。如：递归太多。



Error 是基类型，其他错误类型都继承该类型

### 3.try/catch 用法

如果明确知道某段代码**可能出现某种错误**，那么应该用 `try/catch `包起来，对可能的错误进行处理

如果你名错知道某段代码**一定会发生某种错误**，那就不适合

## 21.2.2 抛出错误

`throw` 操作符可以手动抛出 JS 错误。最常见的用法如：

~~~js
throw new Error('这是一个错误')
~~~

也可以指定具体的错误类型，例如：

~~~js
throw new SyntaxError('xxx 语法错误')
~~~

最常用的错误类型是 Error、RangeError、ReferenceError 和 TypeError

### 抛出自定义错误类型的错误

通过继承 `Error` 的类型可以实现自定义错误类型

~~~js
class CustomError extends Error {
  constructor(message){
    suprer(message);
    this.name = "CustomError"
    this.message = message
  }
}
throw new CustomError('my msg')
~~~

## 21.2.3  error 事件

在任何错误触发时还，都会在 `window`上触发 `error` 事件（向后兼容)

~~~js
window.error(message, url, line) => {
	return false
}
~~~

上面这个例子中 ， `error` 事件返回了 `false` 相当于给 文档 加了一个 `try/catch` 语句
